name: Package

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: package-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: Start9Labs/start-technologies/.github/workflows/build.yml@f7dcde71be804af424350b48c8b73aba03f41321
